//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportNotificationWhattsapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetDayReportIncrease_Result> GetDayReportIncrease(string p_WashCode, Nullable<System.DateTime> p_ReportDate)
        {
            var p_WashCodeParameter = p_WashCode != null ?
                new ObjectParameter("p_WashCode", p_WashCode) :
                new ObjectParameter("p_WashCode", typeof(string));
    
            var p_ReportDateParameter = p_ReportDate.HasValue ?
                new ObjectParameter("p_ReportDate", p_ReportDate) :
                new ObjectParameter("p_ReportDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDayReportIncrease_Result>("GetDayReportIncrease", p_WashCodeParameter, p_ReportDateParameter);
        }
    }
}
