//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerSynchronization_framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int IDCard { get; set; }
        public int IDOwner { get; set; }
        public string CardNum { get; set; }
        public int IDCardStatus { get; set; }
        public int IDCardType { get; set; }
        public int LocalizedBy { get; set; }
        public int LocalizedID { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
