//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerSynchronization_framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventChangerIncrease
    {
        public int IDEventChangerIncrease { get; set; }
        public int IDEventChanger { get; set; }
        public System.DateTime DTime { get; set; }
        public int m10 { get; set; }
        public int b50 { get; set; }
        public int b100 { get; set; }
        public int b200 { get; set; }
        public int b500 { get; set; }
        public int b1000 { get; set; }
        public int b2000 { get; set; }
    
        public virtual EventChanger EventChanger { get; set; }
    }
}
