//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerSynchronization_framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Changers> Changers { get; set; }
        public virtual DbSet<EventChanger> EventChanger { get; set; }
        public virtual DbSet<EventChangerAcquiring> EventChangerAcquiring { get; set; }
        public virtual DbSet<EventChangerCard> EventChangerCard { get; set; }
        public virtual DbSet<EventChangerIncrease> EventChangerIncrease { get; set; }
        public virtual DbSet<EventChangerKind> EventChangerKind { get; set; }
        public virtual DbSet<EventChangerOut> EventChangerOut { get; set; }
    }
}
