//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelDb : DbContext
    {
        public ModelDb()
            : base("name=ModelDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NoticeHistory> NoticeHistory { get; set; }
        public virtual DbSet<NoticeRecipientsGroup> NoticeRecipientsGroup { get; set; }
        public virtual DbSet<NoticeStatus> NoticeStatus { get; set; }
    
        public virtual ObjectResult<GetNoticeRecipient_Result> GetNoticeRecipient(string recipientCode)
        {
            var recipientCodeParameter = recipientCode != null ?
                new ObjectParameter("RecipientCode", recipientCode) :
                new ObjectParameter("RecipientCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNoticeRecipient_Result>("GetNoticeRecipient", recipientCodeParameter);
        }
    }
}
