//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeHistory
    {
        public int IDNoticeHistory { get; set; }
        public string Sender { get; set; }
        public System.DateTime DTimeReceive { get; set; }
        public int IDNoticeRecipientsGroup { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DTimeSent { get; set; }
        public Nullable<int> IDNoticeStatus { get; set; }
    
        public virtual NoticeRecipientsGroup NoticeRecipientsGroup { get; set; }
        public virtual NoticeStatus NoticeStatus { get; set; }
    }
}
