//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Operations = new HashSet<Operation>();
        }
    
        public int IDCard { get; set; }
        public int IDOwner { get; set; }
        public string CardNum { get; set; }
        public int IDCardStatus { get; set; }
        public int IDCardType { get; set; }
        public int LocalizedBy { get; set; }
        public int LocalizedID { get; set; }
    
        public virtual CardStatus CardStatus { get; set; }
        public virtual CardType CardType { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operations { get; set; }
    }
}
