//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardOperation
    {
        public int IDCardOpration { get; set; }
        public int IDState { get; set; }
        public int IDDevice { get; set; }
        public string CardNum { get; set; }
        public System.DateTime DTime { get; set; }
    
        public virtual TerminalState TerminalState { get; set; }
    }
}
