//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountersTotal
    {
        public int IDCountersTotal { get; set; }
        public int IDPost { get; set; }
        public System.DateTime DTime { get; set; }
        public int b10 { get; set; }
        public int b50 { get; set; }
        public int b100 { get; set; }
        public int b500 { get; set; }
        public int b1k { get; set; }
        public int m10 { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
