//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMode
    {
        public int IDEvent { get; set; }
        public Nullable<int> IDMode { get; set; }
        public Nullable<int> RemainLimit { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<System.DateTime> DTimeFinish { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Mode Mode { get; set; }
    }
}
