//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IDEvent { get; set; }
        public int IDPost { get; set; }
        public int IDPostEvent { get; set; }
        public int IDEventKind { get; set; }
        public System.DateTime DTime { get; set; }
    
        public virtual EventKind EventKind { get; set; }
        public virtual Post Post { get; set; }
        public virtual EventCash EventCash { get; set; }
        public virtual EventMode EventMode { get; set; }
        public virtual EventSimple EventSimple { get; set; }
        public virtual EventIncrease EventIncrease { get; set; }
        public virtual EventCollect EventCollect { get; set; }
    }
}
