//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IDEvent { get; set; }
        public int IDPost { get; set; }
        public int IDPostEvent { get; set; }
        public int IDEventKind { get; set; }
        public Nullable<System.DateTime> DTime { get; set; }
    
        public virtual EventKind EventKind { get; set; }
        public virtual Post Post { get; set; }
        public virtual EventCash EventCash { get; set; }
        public virtual EventMode EventMode { get; set; }
        public virtual EventSimple EventSimple { get; set; }
    }
}
