//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCash
    {
        public int IDEvent { get; set; }
        public Nullable<int> tb10 { get; set; }
        public Nullable<int> tb50 { get; set; }
        public Nullable<int> tb100 { get; set; }
        public Nullable<int> tb200 { get; set; }
        public Nullable<int> tb500 { get; set; }
        public Nullable<int> tb1k { get; set; }
        public Nullable<int> tm10 { get; set; }
        public Nullable<int> cb10 { get; set; }
        public Nullable<int> cb50 { get; set; }
        public Nullable<int> cb100 { get; set; }
        public Nullable<int> cb200 { get; set; }
        public Nullable<int> cb500 { get; set; }
        public Nullable<int> cb1k { get; set; }
        public Nullable<int> cm10 { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
