//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMode
    {
        public int IDEvent { get; set; }
        public Nullable<int> IDMode { get; set; }
        public Nullable<int> RemainLimit { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<System.DateTime> DTimeFinish { get; set; }
        public Nullable<System.DateTime> DTimeStart { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> PaymentSign { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string CardTypeCode { get; set; }
        public string CardNum { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Mode Mode { get; set; }
    }
}
