//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCollect
    {
        public int IDEvent { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> m10 { get; set; }
        public Nullable<int> b10 { get; set; }
        public Nullable<int> b50 { get; set; }
        public Nullable<int> b100 { get; set; }
        public Nullable<int> b200 { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
