//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int IDFinance { get; set; }
        public int IDDevice { get; set; }
        public int IDFinanceType { get; set; }
        public System.DateTime DTime { get; set; }
        public int Amount { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string ServerMessage { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual FinanceType FinanceType { get; set; }
    }
}
