//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeHistory
    {
        public int IDNoticeHistory { get; set; }
        public string Sender { get; set; }
        public System.DateTime DTimeReceive { get; set; }
        public int IDNoticeRecipientsGroup { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DTimeSent { get; set; }
        public Nullable<int> IDNoticeStatus { get; set; }
    
        public virtual NoticeRecipientsGroup NoticeRecipientsGroup { get; set; }
        public virtual NoticeStatu NoticeStatu { get; set; }
    }
}
