//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Count_Complete { get; set; }
        public Nullable<int> Count_All { get; set; }
        public string Order1 { get; set; }
        public Nullable<System.DateTime> Date_Ordered { get; set; }
        public string Ordered_By { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
