//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalStateInfo
    {
        public int IDStateInfo { get; set; }
        public int IDState { get; set; }
        public int IDDevice { get; set; }
        public int IDPaymentType { get; set; }
        public System.DateTime DTime { get; set; }
        public int m10 { get; set; }
        public int b50 { get; set; }
        public int b100 { get; set; }
        public int b200 { get; set; }
        public int b500 { get; set; }
        public int b1000 { get; set; }
        public int b2000 { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual TerminalState TerminalState { get; set; }
    }
}
