//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerminalState()
        {
            this.CardOperations = new HashSet<CardOperation>();
            this.TerminalStateInfoes = new HashSet<TerminalStateInfo>();
        }
    
        public int IDState { get; set; }
        public int IDDevice { get; set; }
        public int IDStateType { get; set; }
        public System.DateTime DTimeStart { get; set; }
        public Nullable<System.DateTime> DTimeEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardOperation> CardOperations { get; set; }
        public virtual TerminalStateType TerminalStateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalStateInfo> TerminalStateInfoes { get; set; }
    }
}
