//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAvailableWash
    {
        public int IDUserAvailableWash { get; set; }
        public int IDUser { get; set; }
        public int IDWash { get; set; }
        public int Available { get; set; }
    
        public virtual User User { get; set; }
        public virtual Wash Wash { get; set; }
    }
}
