//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronizationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMode
    {
        public int IDEvent { get; set; }
        public Nullable<int> IDMode { get; set; }
        public Nullable<System.DateTime> DTimeStart { get; set; }
        public Nullable<System.DateTime> DTimeFinish { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> PaymentSign { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string CardTypeCode { get; set; }
        public string CardNum { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Mode Mode { get; set; }
    }
}
