//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardOperations
    {
        public int IDCardOpration { get; set; }
        public int IDState { get; set; }
        public int IDDevice { get; set; }
        public string CardNum { get; set; }
        public System.DateTime DTime { get; set; }
    }
}
